travis:
  secure:
    BINSTAR_TOKEN: nqVrmi5WX188GdLLiKwVdoVOeAr0I9PbxXDmImi5s4Ol7UCsKZi65XiU5OkabWPj/QaF9H0t9VAMVqjXKNPbgLCEsPAuL1chS5gHN3Ex976j/dhG9ZS0YNH797K5XMvgHFAvzMQ0ezBtssW/1ISsUgUj1Xwk8DfhO5b5tIwWNsamXtl1j/jKnSbR0kaVvbd10RyTGdMQucTQkElsWQ1jjMXORjXQ8tqfWElonqwNz5LY6td0aKN/CDhlb6pQ16ToP8w8xBqGrWlx5MoIZNBWU6B2zy130DsZyBG9vDlaJqgw+nuBWkkPyMk8RYPOoFFTAvb/9xaglTzDINylNlKGaTXefht/v/HcCLQ3FnOGpHv8981EfUnwaJeqpm+CfxsD09DuJDLHaDyBAQQckM5MSSJbUzZh/KAhccWs9GDmMJIy/9sdieIZ5/TkctXr6vJ/KSO7z7L5wnxj5YSueetETgGJ53DvT6/nPJpJ+p315APU4WT8rrCOUxkGSJZazLt0Jw09OpA8zKmA6ztrLQwFiz246BKmoaj9/KTG1wBpwHYPF7PW/sER+4hcqTikyLmdLDFAMon4Luhb8Ydx4L0JbWh//1mmUahb+e8d6bfCwGqtfFWbQv2qLH9JqJQYFDX88LGcR8BoXjwlppP7KzidFTD4OUBcwqbWTtePxnDG9LE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
